//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.StudentCourses = new HashSet<StudentCourse>();
        }
    
        public string CourseId { get; set; }
        public int CourseTableId { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}
